DebatNL_BackOffice/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.contrib.auth.views import PasswordResetView
from django.urls import reverse_lazy
from django.views.generic import RedirectView

urlpatterns = []
password_reset_kwargs = {
    'html_email_template_name': 'users/emails/reset_password_html_email.html',
    'from_email': 'Debat.NL Olaf <olaf@debat.nl>'
}

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

urlpatterns += [
    url(
        r'^password_reset/$',
        PasswordResetView.as_view(**password_reset_kwargs),
        name='password_reset'
    ),
    url(r'^', include('django.contrib.auth.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include('users.urls', namespace='users')),
    url(
        r'^configuration/',
        include('backoffice.urls', namespace='configuration')
    ),
    url(
        r'^debatnl-online/',
        include('debatnl_online.urls.urls', namespace='debatnl_online')
    ),
    url(
        r'^debatnl-registration/',
        include('debatnl_registration.urls', namespace='debatnl_registration')
    ),
    url(r'^scans/', include('scans.urls', namespace='scans')),
    url(r'^feedback/', include('feedback.urls', namespace='feedback')),
    url(r'^offers/', include('offers.urls', namespace='offers')),
    url(r'^intakes/', include('intakes.urls', namespace='intakes')),
    url(r'^briefings/', include('briefings.urls', namespace='briefings')),
    url(r'^follow-ups/', include('follow_ups.urls', namespace='follow_ups')),
    url(r'^$', RedirectView.as_view(url=reverse_lazy('feedback:overview')),
        name='main_page'),
    url(r'^planning/', include('planning.urls', namespace='planning')),
    url(r'^schedules/', include('schedules.urls', namespace='schedules')),
    url(r'^ccd/', include('ccd.urls', namespace='ccd')),
    url(
        r'^debatnl-mobile/',
        include('debatnl_mobile.urls', namespace='debatnl_mobile')
    ),
    url(r'^marketing/', include('marketing.urls.urls', namespace='marketing')),
    url(r'^handouts/', include('handouts.urls', namespace='handouts')),
    url(
        r'^declarations/',
        include('declarations.urls', namespace='declarations')
    ),
    url(r'^salaries/', include('salaries.urls', namespace='salaries')),
    url(r'^education/', include('education.urls', namespace='education')),
    url(r'^tinymce/', include('tinymce.urls'))
]

ccd/urls.py
from django.conf.urls import url

from .views import OverviewView, PurchaseOrderView, ExpiredPageView, \
    PersonUpdateView


urlpatterns = [
    url(r'^$', OverviewView.as_view(), name='overview'),
    url(
        r'^purchase-orders/(?P<pk>[0-9a-f-]+)/$',
        PurchaseOrderView.as_view(),
        name='purchase-orders'
    ),
    url(r'^expired/$', ExpiredPageView.as_view(), name='expired-page'),
    url(
        r'^persons/(?P<pk>[0-9]+)/$',
        PersonUpdateView.as_view(),
        name='person-update'
    )
]

feedback/urls.py
from django.conf.urls import url
from feedback.views import OverviewView, FeedbackView, \
    TrainerAverageScoreView, TrainingOuttakeActivation,\
    TrainingOuttakeSubscriptionView

urlpatterns = [
    url(
        r'^training/outtakes/unsubscribe/$',
        TrainingOuttakeSubscriptionView.as_view(),
        name='unsubscribe-training-outtake'
    ),
    url(
        r'^training/outtakes/(?P<training_id>[a-zA-Z0-9-]+)/$',
        TrainingOuttakeActivation.as_view(),
        name='activate-training-outtake'
    ),
    url(
        r'^monthly-average-overview-review-score/$',
        TrainerAverageScoreView.as_view(),
        name='overview_monthly_average_review_score'
    ),
    url(r'^tables-feedback/$', FeedbackView.as_view(), name='tables_feedback'),
    url(r'^$', OverviewView.as_view(), name='overview'),
]

feedback/models.py
import uuid
from django.db import models
from django.utils.translation import ugettext_lazy as _


class JotFormTrainer(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    first_name = models.CharField(max_length=200, blank=True, default='')
    last_name = models.TextField(max_length=200, blank=True, default='')

    class Meta:
        verbose_name = _('Trainer')
        verbose_name_plural = _('Trainers')
        ordering = ('first_name', 'last_name')
        permissions = (
            ('view_all_trainers', 'Can see all trainers'),
        )

    def __str__(self):
        return self.get_full_name()

    def get_full_name(self):
        return f'{self.first_name} {self.last_name}'.strip()


class JotFormTraining(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    date = models.DateField(null=True)
    trainer = models.ForeignKey(JotFormTrainer, on_delete=models.CASCADE)

    class Meta:
        verbose_name = _('Training')
        verbose_name_plural = _('Trainings')
        ordering = ('date',)

    def has_outtake(self):
        name = self.trainer.get_full_name()
        return TrainingOuttake.objects.filter(training_date=self.date,
                                              trainer_name=name).exists()

    def get_average_score(self):
        total_score = 0
        amount_submissions = 0

        for values in self.reviews.values('score'):
            score = values.get('score')
            if score:
                total_score += score
                amount_submissions += 1

        if amount_submissions > 0:
            return total_score / amount_submissions

        return 0


class JotFormTrainingReview(models.Model):
    training_review_id = models.UUIDField(primary_key=True, default=uuid.uuid4,
                                          editable=False)
    training = models.ForeignKey(JotFormTraining, null=True,
                                 on_delete=models.CASCADE,
                                 related_name='reviews')
    reviewer_name = models.CharField(max_length=200, blank=True, default='')
    reviewer_email = models.CharField(max_length=200, blank=True, default='')
    score = models.IntegerField(null=True)
    comment = models.TextField(blank=True, default='')
    resolution = models.TextField(blank=True, default='')
    submission_date = models.DateField(null=True)

    class Meta:
        verbose_name = _('Training review')
        verbose_name_plural = _('Training reviews')


class TrainingOuttake(models.Model):
    STARTED = 'STARTED'
    STOPPED = 'STOPPED'

    STATUS_CHOICES = (
        (STARTED, _('Started')),
        (STOPPED, _('Stopped')),
    )

    training_date = models.DateField(null=True, db_index=True)
    trainer_name = models.CharField(max_length=200, blank=True, default='')
    status = models.CharField(max_length=50, blank=True, default=STARTED,
                              choices=STATUS_CHOICES)

    class Meta:
        index_together = ['training_date', 'trainer_name']


class TrainingOuttakeSubscriber(models.Model):
    SUBSCRIBED = 'SUBSCRIBED'
    UNSUBSCRIBED = 'UNSUBSCRIBED'

    STATUS_CHOICES = (
        (SUBSCRIBED, _('Subscribed')),
        (UNSUBSCRIBED, _('Unsubscribed')),
    )

    subscriber_id = models.UUIDField(primary_key=True, default=uuid.uuid4,
                                     editable=False)
    outtake = models.ForeignKey(TrainingOuttake, on_delete=models.CASCADE,
                                null=True, related_name='subscribers')
    name = models.CharField(max_length=200, blank=True, default='')
    email = models.CharField(max_length=200, blank=True, default='')
    resolution = models.TextField(blank=True, default='')
    training_date = models.DateField(null=True)
    subscription_date = models.DateTimeField(null=True)
    status = models.CharField(max_length=50, blank=True, default=SUBSCRIBED,
                              choices=STATUS_CHOICES)

    class Meta:
        index_together = ['name', 'email', 'training_date']

    def __str__(self):
        return '{} (id: {})'.format(self.name, self.subscriber_id)


class TrainingOuttakeNotification(models.Model):
    INTRO = 'INTRO'
    REMINDER = 'REMINDER'

    NOTIFICATION_TYPE_CHOICES = (
        (INTRO, _('Intro')),
        (REMINDER, _('Reminder')),
    )

    notification_type = models.CharField(max_length=50, blank=True, default='',
                                         choices=NOTIFICATION_TYPE_CHOICES)
    notification_date = models.DateField(db_index=True)
    subscriber = models.ForeignKey(TrainingOuttakeSubscriber,
                                   on_delete=models.CASCADE,
                                   related_name='notifications')

feedback/views.py
import pendulum
from dateutil.relativedelta import relativedelta
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ValidationError
from django.http import JsonResponse
from django.urls import reverse_lazy
from django.utils import timezone
from django.utils.datastructures import OrderedSet
from django.views.generic import ListView
from django.views.generic.base import View, RedirectView, TemplateView

from backoffice.views import BaseEmailView
from feedback.emails import OuttakeIntroEmail, OuttakeReminderEmail
from feedback.models import JotFormTrainer, JotFormTraining, \
    TrainingOuttakeSubscriber
from feedback.utilities.calculations import calculate_average_review_score
from feedback.utilities.training_outtakes import activate_outtake_notifications


class OverviewView(LoginRequiredMixin, ListView):
    template_name = 'feedback/base.html'

    def get_queryset(self):
        cutoff_date = timezone.now() - relativedelta(months=6)
        kwargs = {'jotformtraining__date__gte': cutoff_date}

        if not self.request.user.has_perm('feedback.view_all_trainers'):
            kwargs.update({
                'first_name': self.request.user.first_name,
                'last_name': self.request.user.last_name
            })

        self.queryset = JotFormTrainer.objects.filter(**kwargs).distinct()
        return super().get_queryset()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['years'] = self.get_years()
        return context

    @staticmethod
    def get_years():
        years = OrderedSet()
        for dt in JotFormTraining.objects.dates('date', 'year'):
            if dt.year > 2000:
                years.add(dt.year)

        # This will make sure that the current year is always available,
        # even when there are no reviews in the current year.
        years.add(pendulum.today().year)
        return sorted(years)


class FeedbackView(LoginRequiredMixin, ListView):
    template_name = 'feedback/components/tables-feedback.html'
    model = JotFormTraining

    def get_queryset(self):
        kwargs = {
            'trainer_id': self.request.GET.get('trainer_id'),
            'date__month': self.request.GET.get('month'),
            'date__year': self.request.GET.get('year'),
        }
        self.queryset = JotFormTraining.objects.none()

        if kwargs['trainer_id']:
            self.queryset = JotFormTraining.objects.filter(**kwargs)

        return super().get_queryset()


class TrainerAverageScoreView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        month = request.GET.get('month')
        year = request.GET.get('year')
        trainer = self.get_trainer()
        calculation = calculate_average_review_score(month, year, trainer)
        return JsonResponse(calculation)

    def get_trainer(self):
        pk = self.request.GET.get('trainer_id')
        try:
            trainer = JotFormTrainer.objects.get(pk=pk)
        except (ValidationError, JotFormTrainer.DoesNotExist):
            trainer = None

        return trainer


class TrainingOuttakeActivation(LoginRequiredMixin, RedirectView):
    url = reverse_lazy('feedback:overview')

    def get(self, request, *args, **kwargs):
        try:
            training_id = kwargs.get('training_id')
            training = JotFormTraining.objects.get(id=training_id)
            activate_outtake_notifications(training)
        except JotFormTraining.DoesNotExist:
            pass

        return super().get(request, *args, **kwargs)


class TrainingOuttakeSubscriptionView(TemplateView):
    model = TrainingOuttakeSubscriber
    template_name = 'feedback/unsubscribed.html'

    def get(self, request, *args, **kwargs):
        try:
            pk = request.GET.get('subscriber')
            subscriber = TrainingOuttakeSubscriber.objects.get(pk=pk)
            subscriber.status = TrainingOuttakeSubscriber.UNSUBSCRIBED
            subscriber.save()

        except (TrainingOuttakeSubscriber.DoesNotExist, ValidationError):
            pass

        return super().get(request, *args, **kwargs)


class BaseOuttakeEmailView(BaseEmailView):
    url = 'admin:feedback_trainingouttakesubscriber_change'
    model = TrainingOuttakeSubscriber


class OuttakeIntroEmailView(BaseOuttakeEmailView):
    email_class = OuttakeIntroEmail
    email_name = 'outtake intro'


class OuttakeReminderEmailView(BaseOuttakeEmailView):
    email_class = OuttakeReminderEmail
    email_name = 'outtake intro'

feedback/templates/feedback/base.html
{% extends "backoffice/base.html" %}
{% load sass_tags %}

{% block custom-stylesheets %}
  <link rel="stylesheet" type="text/css" href="{% sass_src 'feedback/sass/base.sass' %}">
{% endblock %}

{% block content %}
  <div class="row filter-container">
      {# FILTER: TRAINERS #}
    <div class="medium-1 column no-right-padding">
      <label class="middle" for="trainers"> Trainer </label>
    </div>

    <div class="medium-2 column no-left-padding">
      <select id="trainers">
        <option value="" selected>Alle</option>

        {% for trainer in object_list %}
          <option value="{{ trainer.id }}">
              {% if trainer.first_name %} {{ trainer.first_name }} {% endif %}
              {% if trainer.middle_name %} {{ trainer.middle_name }} {% endif %}
              {% if trainer.last_name %} {{ trainer.last_name }} {% endif %}
          </option>
        {% endfor %}
      </select>
    </div>

      {# FILTER: TRAINERS #}
    <div class="medium-1 column">
      <label class="text-right middle" for="months"> Maand </label>
    </div>

      {# FILTER: MONTHS #}
    <div class="medium-2 column no-left-padding">
      <select id="months">
        <option value="01"> Januari</option>
        <option value="02"> Februari</option>
        <option value="03"> Maart</option>
        <option value="04"> April</option>
        <option value="05"> Mei</option>
        <option value="06"> Juni</option>
        <option value="07"> Juli</option>
        <option value="08"> Augustus</option>
        <option value="09"> September</option>
        <option value="10"> Oktober</option>
        <option value="11"> November</option>
        <option value="12"> December</option>
      </select>
    </div>

      {# FILTER: YEAR #}
    <div class="medium-1 column">
      <label class="text-right middle" for="years"> Jaar </label>
    </div>
    <div class="medium-2 column no-left-padding end">
      <select id="years">
          {% for year in years %}
            <option value="{{ year }}">{{ year }}</option>
          {% endfor %}
      </select>
    </div>
  </div>

    {# SECTION: AVERAGE REVIEW SCORE OVERVIEW #}
  <section id="overview-average-review-score">
    <div class="row">
      <div id="overview-container" class="medium-9 column">
          {% include 'feedback/components/overview-average-review-score.html' %}
      </div>
    </div>
  </section>

    {# SECTION: FEEDBACK TABLE #}
  <section id="tables-feedback">
    <div class="row column">
      <h4>DE FEEDBACK</h4>
    </div>

    <div class="row column">
      <div id="table-container" class="row column"></div>
    </div>
  </section>


  <script type="application/javascript">
      $(function() {
          var monthSelector = $('#months');
          var yearSelector = $('#years');
          var trainerSelector = $('#trainers');

          monthSelector.val(moment().format('MM'));
          yearSelector.val(moment().format('YYYY'));

          trainerSelector.change(function () {
              updateMonthlyAverageScore(trainerSelector.val(), monthSelector.val(), yearSelector.val());
              updateTrainingDays(trainerSelector.val(), monthSelector.val(), yearSelector.val());
          });

          trainerSelector.ready(function () {
              updateMonthlyAverageScore(trainerSelector.val(), monthSelector.val(), yearSelector.val());
              updateTrainingDays(trainerSelector.val(), monthSelector.val(), yearSelector.val());
          });

          monthSelector.change(function () {
              updateMonthlyAverageScore(trainerSelector.val(), monthSelector.val(), yearSelector.val());
              updateTrainingDays(trainerSelector.val(), monthSelector.val(), yearSelector.val());
          });

          yearSelector.change(function () {
              updateMonthlyAverageScore(trainerSelector.val(), monthSelector.val(), yearSelector.val());
              updateTrainingDays(trainerSelector.val(), monthSelector.val(), yearSelector.val());
          });
      });

      function updateMonthlyAverageScore(trainerId, month, year) {
          var url = "{% url 'feedback:overview_monthly_average_review_score' %}?trainer_id=" + trainerId + "&month=" + month + "&year=" + year;
          $.get(url, function (data) {
              $("#average-score").html(data.average_score);
              $("#amount-submissions").html(data.amount_submissions);

              for (var key in data.occurrences) {
                  if (data.occurrences.hasOwnProperty(key)) {
                      var occurence = data.occurrences[key];
                      $("#category-" + key + " .line").css('width', occurence.percentage);
                      $("#category-" + key + " .amount").html(occurence.count);
                  }
              }
          });
      }

      function updateTrainingDays(trainerId, month, year) {
          var url = "{% url 'feedback:tables_feedback' %}?trainer_id=" + trainerId  + "&month=" + month + "&year=" + year;
          $.get(url, function (data) {
              var tableContainer = $("#tables-feedback");
              tableContainer.html('');
              tableContainer.append(data);
          });
      }
  </script>
{% endblock %}

feedback/templates/feedback/unsubscribed.html
{% load static %}
{% load sass_tags %}
{% load assets %}

<!DOCTYPE html>
<html lang="en" class="grey">
<head>
  <meta charset="UTF-8">
  <title>{% block title %} Debat.NL {% endblock %}</title>

  {# BASE STYLESHEETS #}
  <link rel="stylesheet" type="text/css" href="{% static 'font-awesome/css/font-awesome.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/foundation.min.css' %}">
  <link rel="stylesheet" type="text/css" href="{% sass_src 'backoffice/sass/style.sass' %}">
  <link rel="stylesheet" type="text/css"  href="{% sass_src 'feedback/sass/base.sass' %}">

  {# BASE JAVASCRIPT #}
  <script type="application/javascript" src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
  <script type="application/javascript" src="{% static 'js/foundation.min.js' %}"></script>
</head>

<body>
<div>
  <div class="page-banner">
    <img class="full-bg" src="{% static 'img/banner-presentation.jpg' %}" alt="">
  </div>
</div>

<div class="row column">
  <div id="card-container">
    <div class="columns large-8 large-offset-2 card">
      <div class="page-container">
        <div class="large-4 large-centered text-center">
          <img src="{% static 'img/handshake.png' %}">
        </div>
        <br>
        <div class="large-12 large-centered text-center">
          <p>Uit het oog, maar nooit uit het hart.</p>
          <p>Veel succes met het toepassen van het geleerde!</p>
        </div>
      </div>
    </div>
  </div>
</div>
</body>
</html>