DebatNL_BackOffice/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.contrib.auth.views import PasswordResetView
from django.urls import reverse_lazy
from django.views.generic import RedirectView

urlpatterns = []
password_reset_kwargs = {
    'html_email_template_name': 'users/emails/reset_password_html_email.html',
    'from_email': 'Debat.NL Olaf <olaf@debat.nl>'
}

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

urlpatterns += [
    url(
        r'^password_reset/$',
        PasswordResetView.as_view(**password_reset_kwargs),
        name='password_reset'
    ),
    url(r'^', include('django.contrib.auth.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include('users.urls', namespace='users')),
    url(
        r'^configuration/',
        include('backoffice.urls', namespace='configuration')
    ),
    url(
        r'^debatnl-online/',
        include('debatnl_online.urls.urls', namespace='debatnl_online')
    ),
    url(
        r'^debatnl-registration/',
        include('debatnl_registration.urls', namespace='debatnl_registration')
    ),
    url(r'^scans/', include('scans.urls', namespace='scans')),
    url(r'^feedback/', include('feedback.urls', namespace='feedback')),
    url(r'^offers/', include('offers.urls', namespace='offers')),
    url(r'^intakes/', include('intakes.urls', namespace='intakes')),
    url(r'^briefings/', include('briefings.urls', namespace='briefings')),
    url(r'^follow-ups/', include('follow_ups.urls', namespace='follow_ups')),
    url(r'^$', RedirectView.as_view(url=reverse_lazy('feedback:overview')),
        name='main_page'),
    url(r'^planning/', include('planning.urls', namespace='planning')),
    url(r'^schedules/', include('schedules.urls', namespace='schedules')),
    url(r'^ccd/', include('ccd.urls', namespace='ccd')),
    url(
        r'^debatnl-mobile/',
        include('debatnl_mobile.urls', namespace='debatnl_mobile')
    ),
    url(r'^marketing/', include('marketing.urls.urls', namespace='marketing')),
    url(r'^handouts/', include('handouts.urls', namespace='handouts')),
    url(
        r'^declarations/',
        include('declarations.urls', namespace='declarations')
    ),
    url(r'^salaries/', include('salaries.urls', namespace='salaries')),
    url(r'^education/', include('education.urls', namespace='education')),
    url(r'^tinymce/', include('tinymce.urls'))
]

briefings/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from briefings.views import OverviewView, DeliverableDetail, \
    BriefingCreate, BriefingUpdate, DeliverableMaxTrainerDetail, \
    DeliverableMaxTrainerUpdate, DeliverableMaxTrainerConfirm, \
    BriefingQuestionCreateView, BriefingQuestionUpdateView, \
    QuestionUpdateSuccessView

urlpatterns = [
    url(r'^$', login_required(OverviewView.as_view()), name='overview'),
    url(
        r'^deliverables/(?P<deliverable_id>[0-9]+)/form/$',
        BriefingCreate.as_view(),
        name='form'
    ),
    url(
        r'^deliverables/(?P<deliverable_id>[0-9]+)/' \
        'briefings/(?P<pk>[0-9a-f-]+)/update/$',
        BriefingUpdate.as_view(),
        name='briefing-update'
    ),
    url(
        r'^deliverables/(?P<pk>[0-9]+)/max-trainers/$',
        DeliverableMaxTrainerDetail.as_view(),
        name='deliverable-max-trainers'
    ),
    url(
        r'^deliverables/(?P<pk>[0-9]+)/max-trainers/update/$',
        DeliverableMaxTrainerUpdate.as_view(),
        name='deliverable-max-trainers-update'
    ),
    url(
        r'^deliverables/(?P<pk>[0-9]+)/max-trainers/confirm/$',
        DeliverableMaxTrainerConfirm.as_view(),
        name='deliverable-max-trainers-confirm'
    ),
    url(
        r'^deliverables/(?P<pk>[0-9]+)/$',
        DeliverableDetail.as_view(),
        name='deliverable-detail'
    ),
    url(
        r'^deliverables/(?P<pk>[0-9]+)/questions/create/$',
        BriefingQuestionCreateView.as_view(),
        name='briefing-question-create'
    ),
    url(
        r'^questions/(?P<pk>[0-9a-f-]+)/$',
        BriefingQuestionUpdateView.as_view(),
        name='briefing-question-update'
    ),
    url(
        r'^questions/answer/success/$',
        QuestionUpdateSuccessView.as_view(),
        name='question-update-success'
    )
]

ccd/urls.py
from django.conf.urls import url

from .views import OverviewView, PurchaseOrderView, ExpiredPageView, \
    PersonUpdateView


urlpatterns = [
    url(r'^$', OverviewView.as_view(), name='overview'),
    url(
        r'^purchase-orders/(?P<pk>[0-9a-f-]+)/$',
        PurchaseOrderView.as_view(),
        name='purchase-orders'
    ),
    url(r'^expired/$', ExpiredPageView.as_view(), name='expired-page'),
    url(
        r'^persons/(?P<pk>[0-9]+)/$',
        PersonUpdateView.as_view(),
        name='person-update'
    )
]

briefings/views.py
import pendulum
from django.conf import settings
from django.contrib import messages
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.models import User
from django.db.models import Q
from django.shortcuts import redirect, render, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.utils.decorators import method_decorator
from django.views import View
from django.views.generic import ListView, CreateView, DetailView, \
    UpdateView, TemplateView

from backoffice.constants import GROUP_BRIEFINGS
from backoffice.mixins import GroupAccessMixin
from backoffice.views import BaseEmailView
from briefings.emails.notifications import ChangedBriefingNotification, \
    MaxTrainersNotification, BriefingQuestionNotification, \
    AnswerNotification
from briefings.emails.reminders import BriefingNotAddedReminder, \
    TwoWeeksForDeliveryReminder, NewAddedBriefingReminder
from briefings.tasks import create_briefing_deliveries
from shared.enums import RoleName
from .forms import BriefingFileFormSet, QuestionFormSet, QuestionModelFormSet
from .mixins import BaseBriefingMixin
from .models import Deliverable, Briefing, DeliverableTrainer, \
    DeliverableMembership, DeliverableToken, BriefingQuestion, \
    BriefingQuestionToken


class OverviewView(GroupAccessMixin, ListView):
    """
    List all eligible deliveries for briefings and scans
    """
    template_name = 'briefings/deliverable_list.html'
    access_groups = [GROUP_BRIEFINGS]

    @staticmethod
    def calculate_cutoff_date(page):
        today = pendulum.today(tz=settings.TIME_ZONE)
        cutoff_week = page * 2
        return today.subtract(weeks=cutoff_week)

    def get_current_page(self, page):
        qs = Deliverable.objects.exclude(
            status=Deliverable.WAITING_FOR_APPROVAL
        ).exclude(status=Deliverable.TO_BE_DELETED)
        cutoff_date = self.calculate_cutoff_date(page)
        kwargs = {'delivery__order_date__gte': cutoff_date}
        return qs.filter(**kwargs)

    def has_previous_page(self, page):
        qs = Deliverable.objects.exclude(
            status=Deliverable.WAITING_FOR_APPROVAL
        ).exclude(status=Deliverable.TO_BE_DELETED)
        cutoff_date = self.calculate_cutoff_date(page - 1)
        kwargs = {'delivery__order_date__lte': cutoff_date}
        return qs.filter(**kwargs).exists()

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        page = int(self.request.GET.get('page', 0))
        next_page = page + 1
        context['page'] = next_page
        context['is_prev'] = self.has_previous_page(next_page)
        return context

    def get_queryset(self):
        page = int(self.request.GET.get('page', 0))
        self.queryset = self.get_current_page(page)

        if not self.request.user.has_perm('briefings.view_all_briefings'):
            self.queryset = self.queryset.filter(
                Q(delivery__responsible__email=self.request.user.email) |
                Q(delivery__trainers__email=self.request.user.email)
            ).distinct()

        return super().get_queryset()


class DeliverableDetail(GroupAccessMixin, DetailView):
    model = Deliverable
    template_name = 'briefings/components/modals/deliverable_detail.html'
    access_groups = [GROUP_BRIEFINGS]


class BaseDeliverableMaxTrainerView(DetailView):
    model = Deliverable
    token = None

    def dispatch(self, request, *args, **kwargs):
        try:
            token_key = self.request.GET.get('token')
            self.token = DeliverableToken.objects.get(key=token_key)
        except DeliverableToken.DoesNotExist:
            return render(request, 'briefings/public/expired_token.html')

        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        context['token'] = str(self.token.key)
        return context


class DeliverableMaxTrainerDetail(BaseDeliverableMaxTrainerView):
    template_name = 'briefings/public/max-trainers/base.html'


class DeliverableMaxTrainerUpdate(BaseDeliverableMaxTrainerView):
    template_name = 'briefings/public/max-trainers/update_trainers.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        kwargs = {
            'profile__roles__name': RoleName.TRAINER.value,
            'is_active': True
        }
        trainers = User.objects.filter(**kwargs).all()
        context['trainers'] = trainers.order_by('first_name', 'last_name')
        return context

    def post(self, *args, **kwargs):
        deliverable = self.get_object()

        for key, trainer_id in self.request.POST.items():
            if 'trainers-' in key and trainer_id:
                user = User.objects.get(pk=trainer_id)

                try:
                    trainer = DeliverableTrainer.objects.get(email=user.email)
                except DeliverableTrainer.DoesNotExist:
                    trainer = DeliverableTrainer.objects.create(
                        name=user.get_full_name(),
                        email=user.email
                    )

                DeliverableMembership.objects.create(
                    trainer=trainer, deliverable=deliverable,
                    is_manually_added=True)

        url = reverse('briefings:deliverable-max-trainers-confirm',
                      args=(deliverable.pk,))
        return redirect(f'{url}?token={self.token.key}')


class DeliverableMaxTrainerConfirm(BaseDeliverableMaxTrainerView):
    template_name = 'briefings/public/max-trainers/confirm_update.html'

    def get(self, *args, **kwargs):
        deliverable = self.get_object()
        deliverable.status = deliverable.PENDING
        deliverable.save()

        self.token.delete()
        return super().get(*args, *kwargs)


class BriefingCreate(BaseBriefingMixin, CreateView):
    """
    Create briefings for selected deliverables
    """
    template_name = 'briefings/components/modals/modal_add_briefing.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.POST:
            context['briefing_formset'] = BriefingFileFormSet(
                self.request.POST, self.request.FILES)
        else:
            context['briefing_formset'] = BriefingFileFormSet()
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        briefing_formset = context['briefing_formset']
        deliverable_formset = context['deliverable_formset']

        if briefing_formset.is_valid():
            briefing = form.save()
            briefing_formset.instance = briefing
            briefing_formset.save()

            if deliverable_formset.is_valid():
                deliverable_list = form.cleaned_data.get('deliverables')
                deliverable_formset.instance = briefing
                deliverable_formset.save(deliverable_list)

            return super().form_valid(form)

        return self.form_invalid(form)


class BriefingUpdate(BaseBriefingMixin, UpdateView):
    template_name = 'briefings/components/modals/modal_update_briefing.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.POST:
            context['briefing_formset'] = BriefingFileFormSet(
                self.request.POST, self.request.FILES, instance=self.object)
        else:
            context['briefing_formset'] = BriefingFileFormSet(
                instance=self.object)
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        briefing_formset = context['briefing_formset']
        deliverable_formset = context['deliverable_formset']
        if briefing_formset.is_valid():
            briefing_formset.save()

            if deliverable_formset.is_valid():
                deliverable_list = form.cleaned_data.get('deliverables')
                deliverable_formset.instance = self.object
                deliverable_formset.save(deliverable_list)
            ChangedBriefingNotification(self.object).send()
        return super().form_valid(form)


class BriefingQuestionCreateView(GroupAccessMixin, CreateView):
    template_name = 'briefings/components/modals/question_create.html'
    model = BriefingQuestion
    form_class = QuestionFormSet
    success_url = reverse_lazy('briefings:overview')
    access_groups = [GROUP_BRIEFINGS]

    def get_form(self, form_class=None):
        deliverable = get_object_or_404(Deliverable, pk=self.kwargs.get('pk'))
        formset = self.get_form_class()
        data = self.request.POST
        if data:
            return formset(data, instance=deliverable.briefing)
        return formset(
            queryset=BriefingQuestion.objects.none(),
            instance=deliverable.briefing
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['deliverable'] = get_object_or_404(Deliverable,
                                                   pk=self.kwargs['pk'])
        context['formset'] = context['form']
        return context

    def form_valid(self, formset):
        briefing_questions = formset.save(self.request.user)
        context = self.get_context_data()
        token = BriefingQuestionToken.objects.create(
            deliverable=context['deliverable'],
        )
        token.questions.add(*briefing_questions)
        BriefingQuestionNotification(token).send()
        return redirect(self.success_url)


class BriefingQuestionUpdateView(UpdateView):
    """
    View handles adding answers to briefing questions
    """
    template_name = 'briefings/public/add_answers.html'
    model = BriefingQuestionToken
    form_class = QuestionModelFormSet
    success_url = reverse_lazy('briefings:question-update-success')

    def get_queryset(self):

briefings/templates/briefings/components/modals/deliverable_detail.html
<button class="close-button" data-close aria-label="Close modal" type="button">
  <span aria-hidden="true">&times;</span>
</button>

<div class="row column">
  <h5 class="modal-title">DELIVERY</h5>
  <div class="row">
    <div class="large-8 column end">
      <p class="card-label">Trainer(s)/Gespreksleider(s)</p>
      <div class="card">
        <ul class="card-section">
          {% for trainer in deliverable.delivery.trainers.all %}
            <li>{{ trainer.name }}</li>
          {% endfor %}
        </ul>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="large-8 column end">
      <p class="card-label">Logistiek</p>
      <div class="card">
        <div class="card-section">
          {% if deliverable.briefing %}
            <ul>
              <li>
              {{ deliverable.briefing.time }} &nbsp;
              <span class="small-label blue" id="time-updated-label"></span>
              </li>
              <li>
                <pre>{{ deliverable.briefing.address }}</pre> &nbsp;
                <span class="small-label blue" id="address-updated-label"></span>
              </li>
            </ul>
          {% else %}
            Nog niet bekend
          {% endif %}
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="large-12 column">
      <p class="card-label">Inhoudelijk briefing</p>
      <div class="card">
        <div class="card-section">
          {% if deliverable.briefing %}
            <!-- Previous Reason -->
            {% if deliverable.briefing.previous_reason %}
            <div class="content-section">
              <h6>Wat is de doelgroep en het doel?</h6>
              {{ deliverable.briefing.previous_reason|safe }}
            </div>
            {% endif %}

            <!-- Current Reason -->
            <div class="content-section">
              <h6>Wat is de doelgroep en het doel? <span class="small-label blue" id="reason-updated-label"></span></h6>
              {{ deliverable.briefing.reason|safe }}
            </div>

            {% if deliverable.briefing.previous_program %}
            <!-- Previous Program -->
            <div class="content-section">
              <h6>Wat is het programma?</h6>
              {{ deliverable.briefing.previous_program|safe }}
            </div>
            {% endif %}

            <!-- Current Program -->
            <div class="content-section">
              <h6>Wat is het programma? <span class="small-label blue" id="program-updated-label"></span></h6>
              {{ deliverable.briefing.program|safe }}
            </div>

            <div class="content-section">
              <h6>
                Bijgeleverde bijlage
                <span class="small-label blue" id="files-updated-label"></span>
              </h6>
              {% for file in deliverable.briefing.files.all %}

                <div class="row file-row">
                  <div class="large-1 column">
                    {% if file.get_file_extension == 'pdf' %}
                      <span class="fa fa-file-pdf-o text-danger file-icon"></span>
                    {% elif file.get_file_extension == 'jpeg' %}
                      <span class="fa fa-file-photo-o text-danger file-icon"></span>
                    {% elif file.get_file_extension == 'jpg' %}
                      <span class="fa fa-file-photo-o text-danger file-icon"></span>
                    {% elif file.get_file_extension == 'png' %}
                      <span class="fa fa-file-photo-o text-danger file-icon"></span>
                    {% else %}
                      <span class="fa fa-file text-primary file-icon"></span>
                    {% endif %}
                  </div>

                  <div class="large-7 column">
                    <div class="file-information">
                      <div id="file-name-{{ file.id }}" class="file-name">{{ file.file_name }}</div>
                      <div id="file-size-{{ file.id }}" class="file-size">{{ file.get_size_mb }} MB</div>
                    </div>
                  </div>

                  <div class="large-4 column text-right">
                    <a href="{{ file.file.url }}" target="_blank">
                      <span class="fa fa-cloud-download text-default"></span>
                    </a>
                  </div>
                </div>

              {% endfor %}
            </div>
          {% else %}
            Nog niet bekend
          {% endif %}
        </div>
      </div>
    </div>
  </div>

  {% if deliverable.briefing.questions.exists %}
  <div class="row" id="question-section">
    <div class="large-12 column">
      <p class="card-label">Vragen</p>
      <div class="card">
        <div class="card-section">
          {% for question in deliverable.briefing.questions.all %}
            <div class="question-section">
              <h6 class="question-text">{{ question.question }}</h6>
              <p class="answer-text">{{ question.answer|safe }}</p>

              {% if question.files.exists %}
                <p>Bijgeleverde bijlage</p>
                {% for file in question.files.all %}
                  <div class="row file-row">
                    <div class="large-1 column">
                      {% if file.get_file_extension == 'pdf' %}
                        <span class="fa fa-file-pdf-o text-danger file-icon"></span>
                      {% elif file.get_file_extension == 'jpeg' %}
                        <span class="fa fa-file-photo-o text-danger file-icon"></span>
                      {% elif file.get_file_extension == 'jpg' %}
                        <span class="fa fa-file-photo-o text-danger file-icon"></span>
                      {% elif file.get_file_extension == 'png' %}
                        <span class="fa fa-file-photo-o text-danger file-icon"></span>
                      {% else %}
                        <span class="fa fa-file text-primary file-icon"></span>
                      {% endif %}
                    </div>

                    <div class="large-7 column">
                      <div class="file-information">
                        <div id="file-name-{{ file.id }}" class="file-name">{{ file.filename }}</div>
                        <div id="file-size-{{ file.id }}" class="file-size">{{ file.get_size_mb }} MB</div>
                      </div>
                    </div>

                    <div class="large-4 column text-right">
                      <a href="{{ file.file.url }}" target="_blank">
                        <span class="fa fa-cloud-download text-default"></span>
                      </a>
                    </div>
                  </div>
                {% endfor %}
              {% endif %}
            </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
  {% endif %}

  <div class="row footer">
    {% if deliverable.briefing and deliverable.status != deliverable.TO_BE_DELETED %}
      <div class="large-offset-3 large-9 column">
        <div class="small expanded button-group">
          <button type="button" name="btn-open-modal-questions" class="debat-blue button" data-url="{% url 'briefings:briefing-question-create' deliverable.pk %}">Stel vraag</button>
          <button type="button" id="btn-scan-upload" class="debat-blue button" data-open="confirm-modal-{{ deliverable.id }}">Wijzigen</button>
          <button type="button" class="debat-orange button" data-close>Ok</button>
        </div>
      </div>
    {% else %}
      <div class="large-offset-9 large-3 column">
        <button class="expanded debat-orange small button" data-close>Ok</button>
      </div>
    {% endif %}
  </div>
</div>

{% if deliverable.briefing %}
  <div id="briefing-change-wrapper" class="row">
    {% include 'common/widgets/widget-modal.html' with id='briefing-change' button_name='btn-open-modal-change' append_to='#briefing-change-wrapper' %}
  </div>

  <!-- CONFIRM MODAL -->
  <div class="reveal tiny" id="confirm-modal-{{ deliverable.id }}" data-multiple-opened="true" data-reveal>
    {% include 'briefings/components/modals/sections/confirm_dialog.html' %}
  </div>

  <!-- COMMON MODAL WIDGET -->
  {% include 'common/widgets/widget-modal.html' with id="add-questions" button_name="btn-open-modal-questions" %}

  <script>
    $(function(){
      $('#confirm-modal-{{ deliverable.id }}').foundation();

      $('#modal-container-add-questions').on('closed.zf.reveal', function(){
        $(this).parent('.reveal-overlay').remove();
        $('#modal-container-delivery').load('{{ request.path }}');
      });

      $('#modal-container-delivery').on('closed.zf.reveal', function(){
        $('#modal-container-add-questions').parent('.reveal-overlay').remove();
      });

      // `time` updated label
      var timeUpdatedLabel = $('#time-updated-label');
      var timeUpdatedDate = moment("{{ deliverable.briefing.time_updated_on|date:'Y-m-d' }}");
      if (timeUpdatedDate.isValid()) {
        timeUpdatedLabel.text(`(update ${timeUpdatedDate.format('DD MMMM YYYY')})`);
      }

      // `address` updated label
      var addressUpdatedLabel = $('#address-updated-label');
      var addressUpdatedDate = moment("{{ deliverable.briefing.address_updated_on|date:'Y-m-d' }}");
      if (addressUpdatedDate.isValid()) {
        addressUpdatedLabel.text(`(update ${addressUpdatedDate.format('DD MMMM YYYY')})`);
      }

      // `reason` updated label
      var reasonUpdatedLabel = $('#reason-updated-label');
      var reasonUpdatedDate = moment("{{ deliverable.briefing.reason_updated_on|date:'Y-m-d' }}");
      if (reasonUpdatedDate.isValid()) {
        reasonUpdatedLabel.text(`(update ${reasonUpdatedDate.format('DD MMMM YYYY')})`);
      }

      // `program` updated label
      var programUpdatedLabel = $('#program-updated-label');
      var programUpdatedDate = moment("{{ deliverable.briefing.program_updated_on|date:'Y-m-d' }}");
      if (programUpdatedDate.isValid()) {
        programUpdatedLabel.text(`(update ${programUpdatedDate.format('DD MMMM YYYY')})`);
      }

      // `files` updated label
      var filesUpdatedLabel = $('#files-updated-label');
      var filesUpdatedDate = moment("{{ deliverable.briefing.files_updated_on|date:'Y-m-d' }}");
      if (filesUpdatedDate.isValid()) {
        filesUpdatedLabel.text(`(update ${filesUpdatedDate.format('DD MMMM YYYY')})`);
      }
    });
  </script>
{% endif %}

briefings/templates/briefings/components/modals/question_create.html
<button class="close-button" data-close aria-label="Close modal" type="button">
    <span aria-hidden="true">&times;</span>
</button>

<div class="row column">
  <h5>STEL VRAAG</h5>

  <form id="add-question-form" method="POST">
    {% csrf_token %}
    {{ formset.management_form }}

    <div id="forms-container">
      {% for form in formset %}
        <div id="form-{{ forloop.counter0 }}" class="form initial-form">
          <input type="hidden" name="questions-{{ forloop.counter0 }}-id" id="id_questions-{{ forloop.counter0 }}-id">

          <div class="row">
            <div class="column large-8">
              <label for="id_questions-{{ forloop.counter0 }}-question">Vraag {{ forloop.counter }}</label>
              <textarea name="questions-{{ forloop.counter0 }}-question" id="id_questions-{{ forloop.counter0 }}-question" rows="5" required></textarea>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>

    <br>

    <div class="row footer">
      <div class="large-12 column">
        <div class="small expanded button-group">
          <button type="button" id="add-more-form" class="debat-blue button">Vraag toevoegen</button>
          <button type="button" id="remove-last-form" class="debat-blue button">Vraag verwijderen</button>
          <button type="submit" id="submit-btn" class="debat-orange button">Opslaan</button>
        </div>
      </div>
    </div>
  </form>
</div>

<div id="empty-form" class="empty-forms">
  {% include 'briefings/components/modals/sections/empty_question_form.html' %}
</div>

<script>
  $(function(){
    var formset  = $('#add-question-form');

    // Function to update the `#id_form-TOTAL_FORMS`
    // hidden field
    function updateTotalFormsValue() {
      var formCount = formset.find('.form').length;
      $('#id_questions-TOTAL_FORMS').val(formCount);
    }

    // Handle adding more forms
    $('#add-more-form').click(function() {
      var emptyForm = $('#empty-form').clone();
      var formCount = formset.find('.form').length;
      var newForm= $(emptyForm.html().replace(/__prefix__/g, formCount).replace(/__prefix_form_counter__/g, formCount + 1));
      $('#forms-container').append(newForm);

      updateTotalFormsValue();
    });

    // Handle removing the last form
    $('#remove-last-form').click(function() {
      var forms = formset.find('.form');

      if (forms.length > 1) {
        forms.last().remove();
        updateTotalFormsValue();
      }
    });

    // Handles form submission
    $(formset).submit(function(event){
      event.preventDefault();
      $('#submit-btn').attr('disabled', true);
      var url = "{% url 'briefings:briefing-question-create' deliverable.pk %}";
      var formData = formset.serialize();
      $.post(url, formData, function(){
        $('#modal-container-add-questions').foundation('close');
      });
    });
  });
</script>